# Question1


In [4]:
import numpy as np
import random
matrix= np.array(random.sample(range(1, 50), 20)).reshape(5, 4)
print(matrix)

[[33  2  9 15]
 [21 44 23 30]
 [25  3 38 40]
 [ 5 27 34 24]
 [16 32 26 39]]


In [8]:
print(matrix[4][1])

32


In [11]:
#Printing aniti diagonal elements
for i in range(4):
    print(matrix[i][3-i], end=' ')


15 23 3 5 

In [22]:
#max value in each row
for i in range(5):
    print(np.max(matrix[i]), end=' ')

33 44 40 34 39 

In [21]:
# Filter elements less than or equal to the mean
filtered = matrix[matrix <= mean]
print(filtered)

[ 2  9 15 21 23  3  5 24 16]


In [23]:
#printing clockwise elements
def print_clockwise(matrix):
    if not matrix.size:
        return
    
    top, bottom = 0, matrix.shape[0] - 1
    left, right = 0, matrix.shape[1] - 1
    
    while top <= bottom and left <= right:
        for i in range(left, right + 1):
            print(matrix[top][i], end=' ')
        top += 1
        
        for i in range(top, bottom + 1):
            print(matrix[i][right], end=' ')
        right -= 1
        
        if top <= bottom:
            for i in range(right, left - 1, -1):
                print(matrix[bottom][i], end=' ')
            bottom -= 1
            
        if left <= right:
            for i in range(bottom, top - 1, -1):
                print(matrix[i][left], end=' ')
            left += 1

In [24]:
print_clockwise(matrix)


33 2 9 15 30 40 24 39 26 32 16 5 25 21 44 23 38 34 27 3 

# Question2

In [42]:
#createing random array of 20 floats between 0 and 10
array = np.random.uniform(0, 10, 20)
#printing 2 decimal places
print(np.round(array, 2))

[8.65 3.89 0.65 8.58 0.76 1.24 8.94 5.75 5.74 9.87 0.12 3.14 5.76 8.54
 7.03 5.19 6.03 3.44 8.28 0.49]


In [43]:
min_value = np.min(array)
mean = np.mean(array)   
max_value = np.max(array)
print(f"Min: {min_value:.2f}, Mean: {mean:.2f}, Max: {max_value:.2f}")

Min: 0.12, Mean: 5.11, Max: 9.87


In [44]:
for i in range(20):
    if array[i] < 5:
        array[i] *=array[i]
#print(array)

print(np.round(array, 2))

[ 8.65 15.15  0.42  8.58  0.57  1.55  8.94  5.75  5.74  9.87  0.02  9.87
  5.76  8.54  7.03  5.19  6.03 11.82  8.28  0.24]


In [48]:
def numpy_alternate_sort(array):
    sorted_array = np.sort(array)
    n = len(sorted_array)
    
    result = np.empty(n, dtype=sorted_array.dtype)
    result[0::2] = sorted_array[:(n + 1) // 2]  # Even indices
    result[1::2] = sorted_array[(n + 1) // 2:][::-1]  # Odd indices
    
    return result
print(np.round(numpy_alternate_sort(array),2))

[ 0.02 15.15  0.24 11.82  0.42  9.87  0.57  9.87  1.55  8.94  5.19  8.65
  5.74  8.58  5.75  8.54  5.76  8.28  6.03  7.03]


# problem 3

In [57]:
#Creating the data set of scores of 10 students in 5 subjects
Names = ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack']
Subjects = ['Math', 'Science', 'English']
scores = np.random.randint(50, 100, 10)
import pandas as pd
data ={
    'Names': Names,
    #selecting random subjects for each student
    'Subjects': random.choices(Subjects, k=10),
    'Scores': scores

}
df = pd.DataFrame(data)
print(df)

     Names Subjects  Scores
0    Alice  Science      78
1      Bob  English      73
2  Charlie  English      95
3    David  English      55
4      Eve  English      81
5    Frank  Science      83
6    Grace  English      76
7   Hannah  English      54
8      Ian  Science      84
9     Jack  Science      78


In [60]:
#adding a new column for the grade based on scores
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'
df['Grade'] = df['Scores'].apply(assign_grade)
print(df)

     Names Subjects  Scores Grade
0    Alice  Science      78     C
1      Bob  English      73     C
2  Charlie  English      95     A
3    David  English      55     F
4      Eve  English      81     B
5    Frank  Science      83     B
6    Grace  English      76     C
7   Hannah  English      54     F
8      Ian  Science      84     B
9     Jack  Science      78     C


In [59]:
new_data=df.sort_values(by='Scores', ascending=False, inplace=False)
print(new_data)

     Names Subjects  Scores Grade
2  Charlie  English      95     A
8      Ian  Science      84     B
5    Frank  Science      83     B
4      Eve  English      81     B
0    Alice  Science      78     C
9     Jack  Science      78     C
6    Grace  English      76     C
1      Bob  English      73     C
3    David  English      55     F
7   Hannah  English      54     F


In [52]:
#avg score of each subject
avg_scores = df.groupby('Subjects')['Scores'].mean().reset_index()
print(avg_scores)

  Subjects     Scores
0  English  96.666667
1     Math  87.666667
2  Science  74.250000


In [61]:
def pandas_filter(dataframe, threshold):
    return dataframe[dataframe['Scores'] > threshold]
def grade_to_threshold(grade):
    if grade == 'A':
        return 90
    elif grade == 'B':
        return 80
    elif grade == 'C':
        return 70
    elif grade == 'D':
        return 60
    else:
        return 0
print(pandas_filter(df, grade_to_threshold('B')))

     Names Subjects  Scores Grade
2  Charlie  English      95     A
4      Eve  English      81     B
5    Frank  Science      83     B
8      Ian  Science      84     B


# Problem 4

In [79]:
# 1. Create synthetic dataset
import pandas as pd
import numpy as np
positive_reviews = [
    "Loved every second of it",
    "Absolutely a must-watch film",
    "Great acting and strong story",
    "Beautifully directed and emotional",
    "Amazing soundtrack and visuals",
    "Storyline kept me hooked",
    "Outstanding performances all around",
    "A heartwarming experience overall",
    "Funny, smart, and touching",
    "One of my favorite movies",
    "Really inspiring and well done",
    "An instant classic for sure",
    "A brilliant piece of cinema",
    "Had me smiling throughout",
    "Characters felt so real",
    "Superb in every possible way",
    "A joyful and moving film",
    "It exceeded my expectations",
    "Best movie I’ve seen lately",
    "Cried and laughed with joy",
    "Top-tier storytelling and acting",
    "A thrilling and fun ride",
    "Totally worth the watch",
    "A movie to remember forever",
    "So much better than expected",
    "Left me speechless and happy",
    "Great mix of humor and heart",
    "It was pure entertainment gold",
    "A visual and emotional treat",
    "Impressive from start to finish",
    "Wonderful script and great cast",
    "Touches the soul deeply",
    "Entertaining and well-executed",
    "One of the best endings",
    "Stunning cinematography and plot",
    "Fresh, bold, and brilliant",
    "Absolutely nailed every moment",
    "The plot was gripping throughout",
    "A masterpiece without a doubt",
    "Can’t wait to rewatch it",
    "A movie you can feel",
    "It made my day better",
    "So beautifully put together",
    "A rare gem these days",
    "It had real emotional weight",
    "Everything just worked perfectly",
    "A flawless and heartfelt journey",
    "Elevated my love for movies",
    "An unforgettable cinematic experience",
    "The best two hours spent"
]

negative_reviews = [
    "Completely wasted my time",
    "Boring from start to end",
    "Story made no real sense",
    "Terrible acting and worse plot",
    "Just couldn’t sit through it",
    "Felt like a school project",
    "Dialogue was painfully bad",
    "Plot was full of holes",
    "Worst film I’ve ever seen",
    "Unrealistic and poorly executed",
    "Disappointing in every single way",
    "Too slow and unengaging",
    "Acting felt stiff and unnatural",
    "Nothing exciting ever happened",
    "Predictable and very cliché",
    "I was checking the time",
    "The ending made no sense",
    "I almost fell asleep",
    "Visually dull and unimaginative",
    "Not worth the ticket price",
    "Didn’t live up to hype",
    "It dragged on forever",
    "Unwatchable and messy story",
    "A complete and utter flop",
    "Why was this even made?",
    "Failed to deliver any emotion",
    "Cringe-worthy from start to finish",
    "Horrible writing and bad pacing",
    "Tried too hard, failed anyway",
    "Just a forgettable experience",
    "Waste of a great cast",
    "Couldn’t connect with characters",
    "Disjointed and confusing scenes",
    "Felt like a bad joke",
    "Soundtrack didn’t fit the mood",
    "Left feeling very disappointed",
    "The hype was misleading",
    "Another generic, lazy movie",
    "Felt forced and uninspired",
    "Watched it, regretted it instantly",
    "Just a poorly made movie",
    "Flat characters, no depth",
    "Too many plot conveniences",
    "Didn't care about the story",
    "An empty, soulless experience",
    "The pacing ruined everything",
    "Looked cheap and rushed",
    "Nothing memorable about this one",
    "Bad script ruined potential",
    "Completely lost my interest"
]

reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})
df = df.sample(frac=1, random_state=42).reset_index(drop=True)  # Shuffle
print(df.head())

                             Review Sentiment
0              Felt like a bad joke  negative
1    Terrible acting and worse plot  negative
2            Didn’t live up to hype  negative
3  Everything just worked perfectly  positive
4      It had real emotional weight  positive


In [80]:
# 2. Tokenize using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

In [81]:
# 3. Split into train and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [82]:
# 4. Train Multinomial Naive Bayes and print accuracy
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Test accuracy:", accuracy_score(y_test, y_pred))

Test accuracy: 0.7


In [85]:
# 5. Predict review sentiment function
def predict_review_sentiment(model, vectorizer, review):
    X_new = vectorizer.transform([review])
    return model.predict(X_new)[0]

# Example usage:
print(predict_review_sentiment(model, vectorizer, "Great movie!!."))
print(predict_review_sentiment(model, vectorizer, "It was a terrible film."))

positive
negative


# Problem 5

In [87]:
# 1. Create synthetic dataset
import pandas as pd
import numpy as np

good_feedback = [
    "Absolutely loved this product.",
    "Works perfectly, very satisfied.",
    "Exceeded my expectations.",
    "Great value for the price.",
    "Highly recommend to everyone.",
    "Customer service was excellent.",
    "Fast shipping and well packaged.",
    "Easy to use and reliable.",
    "Quality is top-notch.",
    "Will definitely buy again.",
    "Very happy with my purchase.",
    "Product matches the description.",
    "Five stars, no complaints.",
    "Superb experience overall.",
    "Impressed with the durability.",
    "Setup was quick and simple.",
    "Looks even better in person.",
    "Met all my needs.",
    "Fantastic, couldn't be happier.",
    "A+ seller and product.",
    "Smooth transaction.",
    "Everything arrived on time.",
    "Exactly what I wanted.",
    "Affordable and effective.",
    "Great communication.",
    "Very comfortable to use.",
    "Love the design.",
    "Performs as advertised.",
    "No issues at all.",
    "Would recommend to friends.",
    "Very pleased with the results.",
    "Top quality materials.",
    "Super easy to assemble.",
    "Arrived earlier than expected.",
    "Great for everyday use.",
    "Very intuitive interface.",
    "Product feels premium.",
    "Great addition to my home.",
    "Very sturdy and well made.",
    "Perfect fit for my needs.",
    "Everything works flawlessly.",
    "Very responsive support.",
    "Looks great and works well.",
    "Very practical and useful.",
    "Exactly as described.",
    "Very efficient and fast.",
    "Great for the price.",
    "Very reliable product.",
    "No regrets buying this.",
    "Would purchase again."
]

bad_feedback = [
    "Very disappointed with this product.",
    "Stopped working after a week.",
    "Not worth the money.",
    "Poor quality and cheap materials.",
    "Would not recommend.",
    "Customer service was unhelpful.",
    "Shipping took forever.",
    "Difficult to use and unreliable.",
    "Quality is terrible.",
    "Will not buy again.",
    "Unhappy with my purchase.",
    "Product does not match description.",
    "One star, many complaints.",
    "Terrible experience overall.",
    "Broke after first use.",
    "Setup was confusing and slow.",
    "Looks worse in person.",
    "Did not meet my needs.",
    "Frustrating, wish I could return.",
    "Seller was unresponsive.",
    "Transaction was a hassle.",
    "Everything arrived late.",
    "Not what I wanted.",
    "Expensive and ineffective.",
    "Poor communication.",
    "Very uncomfortable to use.",
    "Hate the design.",
    "Does not perform as advertised.",
    "Many issues with this.",
    "Would not recommend to anyone.",
    "Very disappointed with the results.",
    "Low quality materials.",
    "Difficult to assemble.",
    "Arrived much later than expected.",
    "Not good for everyday use.",
    "Interface is not intuitive.",
    "Product feels cheap.",
    "Regret adding this to my home.",
    "Very flimsy and poorly made.",
    "Does not fit my needs.",
    "Nothing works properly.",
    "Support was not helpful.",
    "Looks bad and works worse.",
    "Not practical or useful.",
    "Not as described.",
    "Very slow and inefficient.",
    "Overpriced for the quality.",
    "Very unreliable product.",
    "Regret buying this.",
    "Will not purchase again."
]

texts = good_feedback + bad_feedback
labels = ['good'] * 50 + ['bad'] * 50

df = pd.DataFrame({'Text': texts, 'Label': labels})
df = df.sample(frac=1, random_state=42).reset_index(drop=True)  # Shuffle

In [88]:
# 2. Preprocess with TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=300, stop_words='english', lowercase=True)
X = vectorizer.fit_transform(df['Text'])
y = df['Label']

In [89]:
# 3. Split into train/test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [92]:
# 4. Train Logistic Regression and print metrics
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         bad       0.29      0.88      0.44         8
        good       0.00      0.00      0.00        17

    accuracy                           0.28        25
   macro avg       0.15      0.44      0.22        25
weighted avg       0.09      0.28      0.14        25



In [96]:
# 5. Preprocess and vectorize function
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

# Example usage:
sample_texts = ["This product is great!", "Terrible quality, not recommended."]
X_sample = text_preprocess_vectorize(sample_texts, vectorizer)
print(model.predict(X_sample))

['good' 'bad']
